
//Welcome
export const TEAM_NAME_CHANGE = 'TEAM_NAME_CHANGE';

//Game
export const HIDE_START_BUTTON = 'HIDE_START_BUTTON';
export const CLOCK_FINISHED = 'CLOCK_FINISHED';
export const ADD_POINT = 'ADD_POINT';
export const NO_ADD_POINT = 'NO_ADD_POINT';
export const START_GAME = 'START_GAME';
export const QUICK_START = 'QUICK_START';

//Game Over
export const NEW_GAME = 'NEW_GAME';
export const START_OVER = 'START_OVER';
export const MAX_SCORE_CHANGED = 'MAX_SCORE_CHANGED';

//Firebase API
export const QUESTION_INPUT_CHANGE_HANDLER = 'QUESTION_INPUT_CHANGE_HANDLER';
export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';
export const FETCH_QUESTIONS_SUCCESS  = 'FETCH_QUESTIONS_SUCCESS';
export const FETCH_QUESTIONS_FAIL = 'FETCH_QUESTIONS_FAIL';
export const FETCH_QUESTIONS_START = 'FETCH_QUESTIONS_START';
export const SUBMIT_QUESTION_SUCCESS  = 'SUBMIT_QUESTION_SUCCESS';
export const SUBMIT_QUESTION_FAIL = 'SUBMIT_QUESTION_FAIL';
export const SUBMIT_QUESTION_START = 'SUBMIT_QUESTION_START';
export const SUBMIT_ANOTHER_QUESTION = 'SUBMIT_ANOTHER_QUESTION';

//Auth
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_START = 'AUTH_START';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const ON_LOGIN_PAGE = 'ON_LOGIN_PAGE';
export const LEAVING_LOGIN_PAGE = 'LEAVING_LOGIN_PAGE';
